/*
 * File: app/store/HomeCarouselItems.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyShop.store.HomeCarouselItems', {
    extend: 'Ext.data.Store',

    requires: [
        'MyShop.model.HomeCarouselItem',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        model: 'MyShop.model.HomeCarouselItem',
        storeId: 'HomeCarouselItems',
        proxy: {
            type: 'ajax',
            url: 'data/home/home_carousel.json',
            reader: {
                type: 'json',
                rootProperty: 'data'
            }
        }
    }
});