/*
 * File: app/view/Home/Home.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyShop.view.Home.Home', {
    extend: 'Ext.navigation.View',
    alias: 'widget.home',

    requires: [
        'Ext.navigation.Bar',
        'Ext.Panel',
        'Ext.carousel.Carousel',
        'Ext.Img',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        navigationBar: {
            docked: 'top',
            hidden: true
        },
        items: [
            {
                xtype: 'panel',
                autoDestroy: false,
                layout: 'vbox',
                scrollable: {
                    direction: 'vertical',
                    directionLock: true
                },
                items: [
                    {
                        xtype: 'carousel',
                        height: 132,
                        id: 'homeCarousel'
                    },
                    {
                        xtype: 'image',
                        height: 50,
                        src: 'resources/image/logo.png'
                    },
                    {
                        xtype: 'searchfield',
                        border: 1,
                        style: 'border-color: #ccc; border-style: solid'
                    },
                    {
                        xtype: 'list',
                        height: 240,
                        id: 'promotionList',
                        itemId: '',
                        itemTpl: [
                            '<div><h2 class="racks-h2">{title}</h2><img width=100% src="{url}"></div>'
                        ],
                        store: 'Promotions'
                    }
                ]
            }
        ]
    }

});