/*
 * File: app/view/Home/Home.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyShop.view.Home.Home', {
    extend: 'Ext.navigation.View',
    alias: 'widget.home',

    requires: [
        'Ext.navigation.Bar',
        'Ext.carousel.Carousel',
        'Ext.Img',
        'Ext.field.Search'
    ],

    config: {
        navigationBar: {
            docked: 'top',
            hidden: true
        },
        items: [
            {
                xtype: 'container',
                autoDestroy: false,
                layout: 'vbox',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'carousel',
                        height: 132,
                        id: 'homeCarousel'
                    },
                    {
                        xtype: 'image',
                        height: 50,
                        src: 'resources/image/logo.png'
                    },
                    {
                        xtype: 'searchfield',
                        border: 1,
                        margin: '5 5 5 30',
                        style: 'border-color: #ccc; border-style: solid;border-radius:20px',
                        width: '70%'
                    }
                ]
            }
        ]
    }

});