/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyShop.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'MyShop.view.Home.Home',
        'Ext.navigation.View',
        'Ext.tab.Bar'
    ],

    config: {
        items: [
            {
                xtype: 'home',
                title: '首页',
                iconCls: 'home'
            },
            {
                xtype: 'container',
                title: '搜索',
                iconCls: 'search',
                itemId: 'tab2'
            },
            {
                xtype: 'container',
                title: '分类',
                iconCls: 'list',
                itemId: 'tab3'
            },
            {
                xtype: 'container',
                title: '购物车',
                iconCls: 'cart',
                itemId: 'tab4'
            },
            {
                xtype: 'container',
                title: '我的',
                iconCls: 'user',
                itemId: 'tab5'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});