/*
 * File: app/controller/Home.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyShop.controller.Home', {
    extend: 'Ext.app.Controller',

    requires: [
        'MyShop.view.Home.Home',
        'Ext.Img',
        'Ext.carousel.Carousel',
        'Ext.MessageBox'
    ],

    config: {
        refs: {
            homeCarousel: '#homeCarousel'
        },

        control: {
            "#homeCarousel": {
                initialize: 'onCarouselInitialize'
            },
            "#promotionList": {
                show: 'onListShow',
                initialize: 'onListInitialize'
            }
        }
    },

    onCarouselInitialize: function(component, eOpts) {
        console.log('onCarouselInitialize');

        component.on({
            delegate: '> image',
            scope: this,
            tap: 'onAutoCarouselItemTap'
        });

        var store = Ext.getStore('HomeCarouselItems');

        store.load({
            callback: function(records, operation, success) {
                var items = [];

                Ext.each(records, function(record) {
                    items.push({
                        xtype: 'image',
                        src: record.get('imgUrl'),
                        record: record
                    });
                });

                component.setItems(items);
            },
            scope: this
        });
    },

    onListShow: function(component, eOpts) {
        console.log('onListShow');
    },

    onListInitialize: function(component, eOpts) {
        console.log('onListInitialize');
    },

    onAutoCarouselItemTap: function(component, e, eOpts) {
        Ext.Msg.alert('Title', component.getRecord().get('imgUrl'), Ext.emptyFn);
    }

});